---
os: linux
language: shell
services: docker

env:
  global:
    - IMAGE_NAME: certhub/certhub
    - IMAGE_VARIANT: dehydrated
    - IMAGE_BUILD_ID: "${IMAGE_VARIANT}-travis-build-${TRAVIS_BUILD_ID}"
    - DOCKER_USERNAME: certhubci
    # travis encrypt DOCKER_PASSWORD=abcdefg[...]
    - secure: "BwfhLkM9l5Iu9/wdVV4lkB5eDemrErplGOOKRE3erx+KFcKOq0CO6IPPui8gEdeGYIp/KWC9th751Gy5vpkIjP9b+kyV15QAX45Eex4AvQK/OvU25zd/XL0xc7RVZzseA3iUgLKsfCrgt+Eh4vomjyVDGkoWvg7HUj1EOrXYCMk1ZO1wyPhfzcBSvbcFpTQU1wMB2I3c3sjJbImQg+QYrOdU5jzCUjSUleoPvR7M/fp0GNnl6Iw06a04/m8IKJPargzYwhcExTnBDR9qJd2sIJ59ByWZdJVzmvxtKRZVcuOg0Hb4K1EVY+YpXd4R8WdDLF90VxIMFm5MfZy47/9/j5KDG9yWf4sjWh6o6cCAwg8GcivSpCoDXGv+fFap224HS+8qvR/Gna3lLM2GO59bi3Kyv0M9kUT8qrWON6qBAgUPnSjSF6qyh+OhWxwe5eePoq8NExKSYe0Ab0668KpQ6o5GfRaTOYHBk6lucu3ODEieroADQtmKR+D2L6TVAsJn0nEw7KlB624g2Js6FUsAJTrvPMEcnqUij5Isds/9wLzqmmJNs5HM8SnrYPT3rRRfe6sIsqo0SrWI9W9H2CGEXKE0yR82UM0ZFEb2h4Aova6bCSfnVPFeShURysf5t8rj+1ZLepe6WQlfDw3A7ljhHUXiQFGkgpCXUyHTTTnORZ8="
    # travis encrypt PRIVATE_SSH_KEY=$(printf %q "$(</path/to/ssh/private.key)")
    - secure: "Omns4E3nPvp+y63K4qMGq3SQXV4YlDDySIqp1hfT4uBPI6ejip9yeXNXAzEq48h9jVIxlyZRlDp1PRSgN2NF3D/++GqCSxs7Ek6lC6f9puWt1uu7zAEV8UTdyYBrIxZ1sFnJ2eBvIfJkJR8IRu3UJm6DFipPprnBzAU3jnZi02ShLsUT5faXyrAUoeycFsfF60AMfnbC2fVoWaC5E8XNx4l+hDbrFUtQ2HpjOAA+wB0G2g+iMGKpSF6/WW5FzfOACSwplhFOs8nYy8uFWScpz6yY3oFPLmlciB1wz00Rwg45r+QeBGZFKIdjKvDRKaW2Qgi7hQtmtozmibZFE/E3CZoA0tgWDpISAIIH6Bus+kLdEniAITs0u43QyHx1lsGWnyGexVQlFtLriH9R4LhmequGTRKK5dR0nyLClKS1afyQNKtBzmBBIzIlkBDZU0Xm13TP9nhDYEWzJ9O+mG4vxoYB2F3wuksYkWtRb2YL8HkV15nxmRE6f2+yM563atZYBMbRkCftcoPFYr70ryBZ4lVU6uTrX8+8NE1AR6nCBX5gyniISTtKL891segVdYo/AXSa2A0zzExdYumT0ehSV7xa8yk0PtNA2sYza4zc20vJe9xG8wUzO7sb8D+5uFqIY+RqxxmN7DP8rihHOSZ54Hc5Xe62pD5YrG2YTTJeIaA="
    # travis encrypt PRIVATE_DIGITALOCEAN_TOKEN=abcdefg[...]
    - secure: "US8F8ITdzaCqiunZvyUiaHcaXrLL+k1mCG0S5iRsk9K66jE092z8FbggQR7JEoIH+pI+Slmr9jDLPyjtYTRMqZm72Q3oSfBNo+NVPb4qSfvO1+Nfj7nhK4sAwnIH3bWlSOpKO2e1t/FGgM47zWCcdULFBrcYsGKnOnCkMZnka1QQq8z84U6WlMjH6I9Ladc8beU56F+a6mxU0lKLZ9hVU/GuR40oPj8XxiT9v1A4GCsZgQvuw10CYYTSILTrvpBr4f7Mkoa0W4gLPjyfBRNdVbD+IBr4xLUaBzotSky4JRERFVAnyxWBrZ2u0E9wQ+kPTEfixQb0R7j7BobuyRntZFExAsS8k1kDn10M4WRGQUsEkcp5suDuUcJbcjAn4yClvas53xt0IYRi2wdn93N3KCLMEsCeS50QILmnRy8zc8E0CQtulrnwinICoYtQptFAcItki8uTa1Ua+ZAGf7lDoVZDebbYlw3teBzQtNwq9EgOkxFvXTl+BSmEEtJvPUqvipBQACgkOh8xYMhXp1s+3ZxHHJdUgk54BTDcMaIUtWrFIC1Sxv7mxBx6YIfx9puStareB769y9HgKAU1LlGsE2oyrqZfG5ggihnq0Mal9pXJz6rSROjsSZ+/PrwHvryEt3bA551EbicRhtZthnfYKP0bkLq0S+8W2NJeGYDnzLA="
    # travis encrypt GH_TOKEN=abcdefg[...]
    - secure: "Su8a8nViwvvg40U/i0E4y9cvLl1L+w4gzheyF7MzF7md7me/crEL7DZ22u06OiohauskQmcuWGzVMe1/1Nlr6El9kY5tMSRapTkGFtpK+vt28AblC1w5NX+eMVw1gFRsCLQs5PPT9NIRal9gW2Kx9WydMZmHRNK+7KGvaqLJHfh6PGqeUVva6d/ROpqDGN0QW8OFuvPZWqIvr5PUtOLehLM54boASXg9vIh44Qk2uiB5EvT5tZ2HN2bs/zk/dbcs2fesiJvLR8hpAZbmk6D2/253Rc200HiZZr1RmKO82Zywz9C20DpaNJTluw2hh9mdYqimkK0PotxmEgepEnyxuQZgrhcrFGAXFcJP98Kdgg6xp4oWeflJCOrt9NQC7Gyxw3xXXfR6Ci1pfProCHUdat+RWgazg1DyZnWMXTWVvYDHlq/8cSFi4Wj7xDSTtUCjn9iZVmpxjq1ULiH4vhuogsElz8nFy6Hos/wFuNkDZrV0wBRYCZxqzrCM+tOCurbNZqJwrkrP71XGTNkW81EWaUC7mYH7LLKc5K5seaPX9mfk4Pp5Uv+fOxPjY1aGURfKGhQV8uvGE/L9qZEa8qTXFyRgllZb3cB5Ha6JGt+ts8MPApJix0pQ/DJm2goSRWSibGVIXnZt9tC1CtJy+4ZksfHdxmdAm5+yaxBJD+c7xKM="

stages:
  - name: Build
  - name: Integration test
  - name: Dockerhub rolling
    if: branch = develop AND type IN (push, cron)
  - name: Github release
    if: branch = latest AND type = push
  - name: Dockerhub release
    if: tag IS present

before_script:
  - docker --version
  - echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin

jobs:
  include:
    - stage: Build
      script:
        - >
            docker build
            --tag "${IMAGE_NAME}:${IMAGE_BUILD_ID}"
            --build-arg build_log_label="Travis CI Build #${TRAVIS_BUILD_NUMBER}"
            --build-arg build_log_url="${TRAVIS_BUILD_WEB_URL}"
            .
        - docker push "${IMAGE_NAME}:${IMAGE_BUILD_ID}"

    - stage: Integration test
      env:
        - DOCKER_COMPOSE_ARGS: >
            "
            -f integration-test/docker-compose.yml
            -f integration-test/docker-compose.travis.yml
            -f integration-test/docker-compose.test-${IMAGE_VARIANT}.travis.yml
            "
      script:
        - docker-compose ${DOCKER_COMPOSE_ARGS} build
        - docker-compose ${DOCKER_COMPOSE_ARGS} run sut

    - stage: Dockerhub rolling
      script:
        - docker pull "${IMAGE_NAME}:${IMAGE_BUILD_ID}"
        - docker tag "${IMAGE_NAME}:${IMAGE_BUILD_ID}" "${IMAGE_NAME}:${IMAGE_VARIANT}-rolling"
        - docker push "${IMAGE_NAME}:${IMAGE_VARIANT}-rolling"

    - stage: Github release
      script:
        - nvm install lts/*
        - npx semantic-release

    - stage: Dockerhub release
      script:
        - export VERSION_PATCH="${TRAVIS_TAG#v}"
        - export VERSION_MINOR="${VERSION_PATCH%.*}"
        - export VERSION_MAJOR="${VERSION_MINOR%.*}"
        - docker pull "${IMAGE_NAME}:${IMAGE_BUILD_ID}"
        - docker tag "${IMAGE_NAME}:${IMAGE_BUILD_ID}" "${IMAGE_NAME}:${IMAGE_VARIANT}-${VERSION_PATCH}"
        - docker tag "${IMAGE_NAME}:${IMAGE_BUILD_ID}" "${IMAGE_NAME}:${IMAGE_VARIANT}-${VERSION_MINOR}"
        - docker tag "${IMAGE_NAME}:${IMAGE_BUILD_ID}" "${IMAGE_NAME}:${IMAGE_VARIANT}-${VERSION_MAJOR}"
        - docker tag "${IMAGE_NAME}:${IMAGE_BUILD_ID}" "${IMAGE_NAME}:${IMAGE_VARIANT}"
        - docker push "${IMAGE_NAME}:${IMAGE_VARIANT}-${VERSION_PATCH}"
        - docker push "${IMAGE_NAME}:${IMAGE_VARIANT}-${VERSION_MINOR}"
        - docker push "${IMAGE_NAME}:${IMAGE_VARIANT}-${VERSION_MAJOR}"
        - docker push "${IMAGE_NAME}:${IMAGE_VARIANT}"
