version: "3.4"

services:
    sut:
        working_dir: /etc/certhub
        depends_on:
          - config
        volumes:
          - config:/etc/certhub
          - ./test:/test

    config:
        working_dir: /etc/certhub
        build:
            context: ./config
        volumes:
          - config:/etc/certhub
          - ./test:/test

    tor:
        build:
            context: ./tor
        expose:
          - "9050"

volumes:
    config:
