---
name: Build and run integration tests on pull requests

# yamllint disable-line rule:truthy
on:
  pull_request:

jobs:
  build:
    uses: ./.github/workflows/container-image.yml

  test:
    uses: ./.github/workflows/integration-test.yml
